template: true   # required for local templates
valuesFilePath: ./values.yaml

resources:
  - name: docker_image
    type: Image
    configuration:
      registry: {{ .Values.docker.dockerIntegrationName }}
      imageName: {{ .Values.docker.imageName }}
      imageTag: {{ .Values.docker.imageTag }}
      autoPull: true

pipelines:
  - name: {{ .Values.docker.pipelineName }}
    steps:
      - name: run_image
        type: Bash
        configuration:
          inputResources:
            - name: docker_image
          runtime:
            type: host
          nodePool: default-dynamic-nodepool
        execution:
          onExecute:
#            - curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.19.0/kind-linux-amd64
#            - chmod +x ./kind
#            - sudo mv ./kind /usr/local/bin/kind
#            - kind create cluster -n test-k8s-integration
            - git clone https://github.com/kubearmor/KubeArmor.git
            - cd KubeArmor/contribution/k3s
            - chmod +x install_k3s.sh
            - ./install_k3s.sh
            - curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
            - curl -LO "https://dl.k8s.io/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl.sha256"
            - echo "$(cat kubectl.sha256)  kubectl" | sha256sum --check
            - sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
            - kubectl version --client
            - kubectl wait --for=condition=Ready nodes --all --timeout=120s
            - kubectl get all -A
            - curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
            - chmod 700 get_helm.sh
            - ./get_helm.sh
            - docker run rajasahil/accuknox-cli:v1 install
