template: true   # required for local templates
valuesFilePath: ./values.yaml

resources:
  - name: docker_image
    type: Image
    configuration:
      registry: {{ .Values.docker.dockerIntegrationName }}
      imageName: {{ .Values.docker.imageName }}
      imageTag: {{ .Values.docker.imageTag }}
      autoPull: true

pipelines:
  - name: {{ .Values.docker.pipelineName }}
    steps:
      - name: run_image
        type: Bash
        configuration:
          inputResources:
            - name: docker_image
        execution:
          onExecute:
            - docker run rajasahil/accuknox-cli:v1 install
            - curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
            - chmod 700 get_helm.sh
            - ./get_helm.sh