template: true   # required for local templates
valuesFilePath: ./values.yaml

resources:
  - name: docker_image
    type: Image
    configuration:
      registry: {{ .Values.docker.dockerIntegrationName }}
      imageName: {{ .Values.docker.imageName }}
      imageTag: {{ .Values.docker.imageTag }}
      autoPull: true

pipelines:
  - name: {{ .Values.docker.pipelineName }}
    steps:
      - name: run_image
        type: Bash
        configuration:
          inputResources:
            - name: docker_image
        execution:
          onExecute:
            - docker run rajasahil/accuknox-cli:v1 install


      - name: helmDeployStep
        type: HelmDeploy
        configuration:
          helmVersion: 3
          namespace: kps
          releaseName: kps
          dryRun: true
          integrations:
            - name: default-dynamic-nodepool
          inputResources:
            - name: prometheus-community/kube-prometheus-stack
        execution:
          onStart:
            - echo "Preparing for work..."
          onSuccess:
            - echo "Job well done!"
          onFailure:
            - echo "uh oh, something went wrong"
          onComplete: #always
            - echo "Cleaning up some stuff"