template: true   # required for local templates
valuesFilePath: ./values.yaml

resources:
  - name: docker_image
    type: Image
    configuration:
      registry: {{ .Values.docker.dockerIntegrationName }}
      imageName: {{ .Values.docker.imageName }}
      imageTag: {{ .Values.docker.imageTag }}
      autoPull: true

pipelines:
  - name: {{ .Values.docker.pipelineName }}
    steps:
      - name: run_image
        type: Bash
        configuration:
          inputResources:
            - name: docker_image
        execution:
          onExecute:
            - docker_image --help