template: true   # required for local templates
valuesFilePath: ./values.yaml

resources:
  - name: docker_image
    type: Image
    configuration:
      registry: {{ .Values.docker.dockerIntegrationName }}
      imageName: {{ .Values.docker.imageName }}
      imageTag: {{ .Values.docker.imageTag }}
      autoPull: true

  - name: runtime_security_task
    type: GitRepo
    configuration:
      path: {{ .Values.myRepo.path }}
      gitProvider: {{ .Values.myRepo.gitProvider }}
      branches:
        include: {{ .Values.myRepo.mainBranch }}
      cloneProtocol: {{ .Values.myRepo.protocol }}
      buildOn:
        commit: {{ .Values.myRepo.buildOnCommit }}

pipelines:
  - name: {{ .Values.docker.pipelineName }}
    steps:
      - name: test_{{ .Values.task.name }}
        type: Bash
        configuration:
          inputResources:
            - name: docker_image
            - name: runtime_security_task
          runtime:
            type: host
        execution:
          onExecute:
            - task: $res_runtime_security_task_resourcePath
              id: runtime_sec
              input:
                ignore-paths: "/bin"