installTaskRepo:
  gitProvider: install_task
  path: rajaSahil/install-task
  mainBranch: main
  protocol: https
  buildOnCommit: true

reportTaskRepo:
  gitProvider: report_task
  path: rajaSahil/report-task
  mainBranch: main
  protocol: https
  buildOnCommit: true


docker:
  dockerIntegrationName: myDocker
  imageName: rajasahil/accuknox-cli
  imageTag: v1
  pipelineName: test_report

pipeline:
  name: runtime_security

task:
  installTask: install_task
  reportTask: report_task