myRepo:
  gitProvider: jfrog_demo_report
  path: rajaSahil/jfrog-demo-report
  mainBranch: main
  protocol: https
  buildOnCommit: true


docker:
  dockerIntegrationName: myDocker
  imageName: rajasahil/accuknox-cli
  imageTag: v1
  pipelineName: test_report

task:
  name: runtime_security