myRepo:
  gitProvider: jfrog_demo_report
  path: rajaSahil/accuknox-cli


docker:
  dockerIntegrationName: myDocker
  imageName: rajasahil/accuknox-cli
  imageTag: report
  pipelineName: test_report

